export enum EBillingStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum EBillingType {
  SESSION = 'SESSION',
  MONTHLY = 'MONTHLY',
  PACKAGE = 'PACKAGE',
  MEMBERSHIP = 'MEMBERSHIP',
}
